services:
  grafana:
    image: grafana/grafana
    restart: unless-stopped
    volumes:
      - ./grafana-data:/var/lib/grafana
  influxdb:
    image: influxdb:latest
    restart: unless-stopped
    volumes:
      - ./influxdb-data:/var/lib/influxdb2
      - ./influxdb-config:/etc/influxdb2
  tunnel:
    image: cloudflare/cloudflared:latest
    restart: unless-stopped
    command: tunnel run --token ${TUNNEL_TOKEN}
